name: Android

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release
  QT_VERSION: "6.3.1"
  QT_ARCH: "android_arm64_v8a"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{runner.workspace}}/Qt
          key: qt-${{env.QT_VERSION}}-${{env.QT_ARCH}}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{steps.cache-qt.outputs.cache-hit}}
          version: ${{env.QT_VERSION}}
          arch: ${{env.QT_ARCH}}

      # https://doc.qt.io/qt-6/android-getting-started.html
      - name: Install Android SDK
        run: sdkmanager --install "cmdline-tools;latest" "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;22.1.7171670"

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: ${{runner.workspace}}/Qt/$QT_VERSION/$QT_ARCH/bin/qt-cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ${{runner.workspace}}/Qt/$QT_VERSION/$QT_ARCH/bin/qt-cmake --build . --config $BUILD_TYPE

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: spotify-qt-quick
          path: ${{runner.workspace}}/spotify-qt-quick
